steps:
  # Step 1: Install Node.js dependencies using npm
  - name: 'node:14'
    entrypoint: 'npm'
    args: ['install']

  # Step 2: Build the React app
  - name: 'node:14'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Step 3: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/housekeeping-management', '.']

images:
  - 'gcr.io/$PROJECT_ID/housekeeping-management'

